# Generated by Django 2.2.1 on 2019-05-29 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_album', models.CharField(default=None, max_length=50, null=True)),
                ('start_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_trask', models.CharField(default=None, max_length=4)),
                ('size', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='MusicBand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=255)),
                ('age', models.IntegerField()),
                ('style', models.CharField(default=None, max_length=255)),
                ('album', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='album', to='hw21.Album')),
                ('track', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='track', to='hw21.Track')),
            ],
        ),
    ]
