# Generated by Django 2.2.1 on 2019-05-29 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hw21', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='musicband',
            name='track',
        ),
        migrations.AddField(
            model_name='album',
            name='track',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='track', to='hw21.Track'),
        ),
    ]
