# Generated by Django 2.2.1 on 2019-05-29 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hw21', '0003_auto_20190529_1145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musicband',
            name='album',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='persons', to='hw21.Album'),
        ),
    ]
