# Generated by Django 2.2.1 on 2019-05-29 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hw21', '0004_auto_20190529_1148'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='musicband',
            name='album',
        ),
        migrations.AddField(
            model_name='musicband',
            name='album',
            field=models.ManyToManyField(null=True, related_name='persons', to='hw21.Album'),
        ),
    ]
